# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = app/database/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Add the above in the form [yy]_[mm]_[dd]_[hh][MM] when you want to use UTC datetime prefix format
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value is passed to ZoneInfo()
# leave blank for localtime
# timezone = UTC

# version path separator; As mentioned above, this is the character used to separate version paths
# default is os.pathsep (i.e. ; for Windows and : for Linux/MacOS)
version_path_separator = os

# version locations, defaults to: %(here)s/versions
version_locations = %(here)s/versions

# the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

# sqlalchemy.url = driver://user:pass@localhost/dbname
# Use a placeholder here; connection.py resolves the real path
sqlalchemy.url = sqlite:///./visual_learner.db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
