import networkx as nx
from typing import List, Dict, Any
from sqlalchemy.orm import Session
from app.models import Document, Node, Edge, Quiz

def build_and_persist_graph(
    db: Session,
    doc: Document,
    themes: List[Dict[str, Any]],
    connections: List[Dict[str, str]],
) -> nx.Graph:
    """Build a NetworkX graph from LLM-extracted themes, persist to SQLite."""
    G = nx.Graph()
    theme_name_to_id: Dict[str, str] = {}

    # Create nodes
    for theme in themes:
        name = theme["name"]
        summary = theme.get("summary", "")
        node_db = Node(
            document_id=doc.id,
            label=name,
            summary=summary,
            weight=5,
            color="#a5d8ff",
        )
        db.add(node_db)
        db.flush()  # get autogenerated id
        theme_name_to_id[name] = node_db.id
        G.add_node(node_db.id, label=name, summary=summary, size=25, color="#a5d8ff")

    # Create edges from LLM relationships
    seen_pairs = set()
    for conn in connections:
        src_name = conn.get("source")
        tgt_name = conn.get("target")
        if src_name not in theme_name_to_id or tgt_name not in theme_name_to_id:
            continue
        # deduplicate undirected
        pair = tuple(sorted([src_name, tgt_name]))
        if pair in seen_pairs:
            continue
        seen_pairs.add(pair)

        src_id = theme_name_to_id[src_name]
        tgt_id = theme_name_to_id[tgt_name]
        edge_db = Edge(
            document_id=doc.id,
            source_id=src_id,
            target_id=tgt_id,
            weight=1.0,
        )
        db.add(edge_db)
        G.add_edge(src_id, tgt_id, weight=1.0)

    # Fallback: fully connect if no edges — every graph needs edges!
    node_ids = list(theme_name_to_id.values())
    if len(node_ids) > 1 and G.number_of_edges() == 0:
        for i in range(len(node_ids) - 1):
            edge_db = Edge(
                document_id=doc.id,
                source_id=node_ids[i],
                target_id=node_ids[i + 1],
                weight=0.5,
            )
            db.add(edge_db)
            G.add_edge(node_ids[i], node_ids[i + 1], weight=0.5)

    # Compute centrality for sizing
    if G.number_of_nodes() > 0:
        centrality = nx.degree_centrality(G)
        for node_id, cent in centrality.items():
            node_db = db.query(Node).filter(Node.id == node_id).first()
            if node_db:
                node_db.weight = max(1, min(10, int(cent * 10) + 3))

    db.commit()
    return G

def persist_quizzes(
    db: Session,
    doc_id: str,
    quizzes_payload: Dict[str, List[Dict[str, Any]]],
):
    """Persist LLM-generated quiz questions to SQLite."""
    for node_id, questions in quizzes_payload.items():
        for q in questions:
            quiz_db = Quiz(
                document_id=doc_id,
                node_id=node_id,
                question=q.get("question", ""),
                options=str(q.get("options", [])),
                correct_index=q.get("correct_index", 0),
            )
            db.add(quiz_db)
    db.commit()
